application: swapp-site
version: 1
runtime: python27
api_version: 1
threadsafe: No

builtins:
- appstats: off
- remote_api: off
- deferred: on

libraries:
- name: jinja2
  version: "latest"
- name: lxml
  version: "latest" # or 2.3: see https://developers.google.com/appengine/docs/python/tools/libraries27

handlers:
- url: /(favicon\.ico|fb-channel\.html|crossdomain\.xml|robots\.txt)
  static_files: static/\1
  upload: static/.*

- url: /static
  static_dir: static

- url: /.*
  script: main.application